CREATE SEQUENCE sq_funcao_func INCREMENT 1 START 1
;

CREATE TABLE TB_FUNCAO_FUNC ( 
	ID_FUNCAO_FUNC integer DEFAULT NEXTVAL('"sq_funcao_func"'::TEXT) NOT NULL,
	DAT_CRIADO timestamp,
	DAT_DESATIVADO timestamp,
	COD_FUNCAO varchar(2) NOT NULL,
	DSC_FUNCAO char(100) NOT NULL,
	FLG_ATIVO varchar(1) DEFAULT 'S'
)
TABLESPACE PG_DEFAULT
;

ALTER TABLE TB_FUNCAO_FUNC ADD CONSTRAINT PK_FUNCAO 
	PRIMARY KEY (ID_FUNCAO_FUNC)
;


